<?php
/**
 * @file podio_webform.module
 * TODO: Enter file description here.
 */
require_once __DIR__ . '/vendor' . '/autoload.php';
 /**
  * Implements hook_menu().
  */
 function podio_webform_menu() {
  $items['admin/config/podio_webform'] = array(
      'title' => t('Podio Webform'),
      'description' => t('Provides the configuration page for the webform to podio module for issue tracking.'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('podio_webform_admin_settings'),
      'access arguments' => array('access administration pages'),
      'file' => 'podio_webform.admin.inc',
      'file path' => drupal_get_path('module', 'podio_webform'),
  );

   return $items;
 }


/**
 * Implements hook_webform_submission_insert().
 *  * Note that this hook is called after a submission has already been saved to
 * the database. If needing to modify the submission prior to insertion, use
 * hook_webform_submission_presave().
 *
 * @param $node
 *   The Webform node on which this submission was made.
 * @param $submission
 *   The Webform submission that was just inserted into the database.
 */
function podio_webform_webform_submission_insert($node, $submission) {
  $data = $submission -> data;
  $webform = $node -> webform;

  $values = array();
  $components = array();
  foreach($webform['components'] as $k => $v ){
    $components[$k]['formkey'] = $v['form_key'];
    $components[$k]['name'] = $v['name'];
    if($v['type'] == 'select' ){

    }
  }
  foreach($data as $k => $v){
    $components[$k]['value'][] = $v['value'];
  }
  dpm($submission);
  dpm($node);
  dpm($webform);
  dpm($data);
  dpm($components);

}


